memodir = "$HOME/.config/memo/notes"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "grep -nH ${PATTERN} ${FILES}"
memotemplate = "$HOME/.config/memo/templates/md.txt"
assetsdir = "."
pluginsdir = "$HOME/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
