version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      nix-flake-inputs:
        patterns:
          - "*"
