[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_fit = 'go'
hook_add = '''
    autocmd FileType go setl nolist
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
