# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'


# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ghifarit53/tokyonight-vim'


# ステータスバー
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# ファイラー
[[plugins]]
repo = 'scrooloose/nerdtree'


# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'


# コメント
[[plugins]]
repo = 'tpope/vim-commentary'


# 無駄なスペース削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'


# ale
[[plugins]]
repo = 'dense-analysis/ale'


# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
merged = 0


# move cursol
[[plugins]]
repo = 'easymotion/vim-easymotion'


[[plugins]]
repo = 'jiangmiao/auto-pairs'


[[plugins]]
repo = 'vim-jp/vimdoc-ja'


# Golang
[[plugins]]
repo = 'mattn/vim-goimports'


# Ruby
[[plugins]]
repo = 'slim-template/vim-slim'
