# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'


# カラースキーム
[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'


# ステータスバー
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


# Git
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'


# ファイラー
[[plugins]]
repo = 'scrooloose/nerdtree'


# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'


# コメント
[[plugins]]
repo = 'tpope/vim-commentary'


# 無駄なスペース削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# LSP
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'


# ale
[[plugins]]
repo = 'dense-analysis/ale'


# Golang
[[plugins]]
repo = 'mattn/vim-goimports'


# Ruby
[[plugins]]
repo = 'tpope/vim-endwise'
