add_newline = true
format = "$time$all"

[aws]
disabled = true

[cmd_duration]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
format = "with [Go ($version )]($style)"

[nodejs]
format = "with [Node ($version )]($style)"

[package]
disabled = true

[python]
format = "with [Python ($version )]($style)"

[ruby]
format = "with [Ruby ($version )]($style)"

[rust]
format = "with [Rust ($version )]($style)"

[time]
disabled = false
format = '[\[$time\]]($style) '
style = "bold blue"
