add_newline = true
format = "$time$all"
command_timeout = 2000

[aws]
disabled = true

[cmd_duration]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
format = '[Go ($version )]($style)'
style = 'bold cyan'

[nodejs]
format = '[Node ($version )]($style)'

[package]
disabled = true

[python]
format = '[$pyenv_prefix($version )(\($virtualenv\) )]($style)'
pyenv_version_name = true

[ruby]
format = '[Ruby ($version )]($style)'

[rust]
format = '[Rust ($version )]($style)'

[time]
disabled = false
format = '[\[$time\]]($style) '
style = 'bold blue'
