check_go_version() {
  if [ ! $(command -v go) ]; then
    return
  fi
  local latest_version=$(curl --silent https://go.dev/VERSION\?m=text | head -1)
  local current_version=$(go version | awk '{print $3}')
  if [ "${latest_version}" != "${current_version}" ]; then
    echo "new release of go is available: ${current_version} -> ${latest_version}"
  fi
}
check_go_version
