return {
  "nvim-treesitter/nvim-treesitter",
  branch = "master",
  lazy = false,
  build = ":TSUpdate",
  dependencies = {
    "RRethy/nvim-treesitter-endwise",
    -- "nvim-treesitter/nvim-treesitter-refactor",
    -- "nvim-treesitter/nvim-treesitter-context",
    -- "folke/twilight.nvim",
  },
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "bash",
        "c",
        "comment",
        "css",
        "diff",
        "dockerfile",
        "git_config",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "html",
        "java",
        "javascript",
        "json",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "proto",
        "python",
        "ruby",
        "rust",
        "sql",
        "toml",
        "tsx",
        "typescript",
        "typespec",
        "vim",
        "yaml",
      },
      auto_install = true,
      highlight = {
        enable = true,
      },
      endwise = {
        enable = true,
      },
    })
  end,
}
